### ISSUE TITLE
What does your podcasting/editing setup look like?

### ISSUE THREAD

**Issue by thexavismith** [iChris/ama#2]

**Comment by iChris** [comment]
It's pretty simple these days. 
- 27" iMac: Smartest decision to go in on a desktop Mac. Apple is taking forever to release updated laptops.
- A Focusrite 18i8: overkill really.
- A pair of Sennheiser HD 280 pro headphones: due for some new ones as these are 6+ years old and starting to fall apart.
- An old desk hand-me-down from my dad's office.
- A chair of some sort from Costco.
- Logic Pro X
- Dropbox for getting/sending audio

I'd go into more detail but then I'd have to start charging you by the hour. ;)
