### ISSUE TITLE
What have you found to make your business successful enough to make a living?

### ISSUE THREAD

**Issue by thexavismith** [iChris/ama#3]

**Comment by iChris** [comment]
I would define what I'm doing right now as "scrapping by" more than "successful enough to make a living", but that's probably semantics. See also AMA #4.

If I had to give myself advice 5 years ago when I started this thing - as well as me yesterday and right - it would sound like this, said in boring dad business advice voice:
- Have 3-5 months of money for a rainy day/week/month before you jump in.
- Respond to emails/phone calls within 3-5 hours
- Tell clients exactly what you're going to do and when you'll do it.
- Follow through on what you said you're going to do and when you said you'd do it.
- Charge more than you think you should.
- Remember to send out invoices monthly. You can't get paid if they don't know they're supposed to pay you.
- Keep your expenses low.
- Unless you already have a very high level skill in a specific area, start with a wide net for the type of clients and narrow your focus over time. 

I could go on but then it would start to sound like a [Medium](https://medium.com) think piece. :)
