### ISSUE TITLE
Do you ever think of going to work for "the man"?

### ISSUE THREAD

**Issue by thexavismith** [iChris/ama#4]

**Comment by iChris** [comment]
Probably every 3-4 months. Particularly when bills pile up or I think about vacation days where you get paid even though you're on vacation or one of us has a tooth related expense and I remember having dental coverage and not worrying about things like that.

I'm enjoying working for myself overall and trying to remember the positives - getting to walk my kids to/from school, not having to start a car in -35C winter, nobody else deciding what I do each day - more than focusing on the negatives. 

It's been 5 years of working on my own business now and my wife and I said we'd do a proper evaluation after 5 years. So if/when we get around to doing that, we'll see. Might have to dust off the old resume. :)
